apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sentences-name
    mode: name
    app.kubernetes.io/part-of: sentences
    version: v1
  name: name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentences-name
      mode: name
      app.kubernetes.io/part-of: sentences
      version: v1
  template:
    metadata:
      labels:
        app: sentences-name
        mode: name
        app.kubernetes.io/part-of: sentences
        version: v1
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8000'
        prometheus.io/path: '/metrics'
    spec:
      containers:
      - image: michaelvl/sentences:v1
        name: name
        env:
        - name: "SENTENCE_MODE"
          value: "name"
        - name: "SENTENCE_RANDOM_SVC_URL"
          value: "http://httpbin.org/bytes/1"
        - name: "SENTENCE_RANDOM_SVC_URL2"
          value: "http://httpbin.org/status/404"
        - name: "SENTENCE_RANDOM_SVC2_PROBABILITY"
          value: "0.1"
---
