apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sentences
    mode: sentence
    app.kubernetes.io/part-of: sentences
  name: sentences
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentences
      mode: sentence
      app.kubernetes.io/part-of: sentences
  template:
    metadata:
      labels:
        app: sentences
        mode: sentence
        app.kubernetes.io/part-of: sentences
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8000'
        prometheus.io/path: '/metrics'
    spec:
      containers:
      - image: michaelvl/sentences:v1
        name: sentences
        env:
        - name: "SENTENCE_MODE"
          value: "sentence"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sentences
    mode: sentence
    app.kubernetes.io/part-of: sentences
  name: sentences
spec:
  ports:
  - name: api
    port: 5000
    protocol: TCP
    targetPort: 5000
    appProtocol: http
  selector:
    app: sentences
    mode: sentence
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sentences-age
    mode: age
    app.kubernetes.io/part-of: sentences
  name: age
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentences-age
      mode: age
      app.kubernetes.io/part-of: sentences
  template:
    metadata:
      labels:
        app: sentences-age
        mode: age
        app.kubernetes.io/part-of: sentences
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8000'
        prometheus.io/path: '/metrics'
    spec:
      containers:
      - image: michaelvl/sentences:v1
        name: age
        env:
        - name: "SENTENCE_MODE"
          value: "age"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sentences-age
    mode: age
    app.kubernetes.io/part-of: sentences
  name: age
spec:
  ports:
  - name: api
    port: 5000
    protocol: TCP
    targetPort: 5000
    appProtocol: http
  selector:
    app: sentences-age
    mode: age
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sentences-name
    mode: name
    app.kubernetes.io/part-of: sentences
    version: v1
  name: name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentences-name
      mode: name
      app.kubernetes.io/part-of: sentences
      version: v1
  template:
    metadata:
      labels:
        app: sentences-name
        mode: name
        app.kubernetes.io/part-of: sentences
        version: v1
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8000'
        prometheus.io/path: '/metrics'
    spec:
      containers:
      - image: michaelvl/sentences:v1
        name: name
        env:
        - name: "SENTENCE_MODE"
          value: "name"
        - name: "SENTENCE_RANDOM_SVC_URL"
          value: "https://httpbin.org/bytes/1"
        - name: "SENTENCE_RANDOM_SVC_URL2"
          value: "https://httpbin.org/status/404"
        - name: "SENTENCE_RANDOM_SVC2_PROBABILITY"
          value: "0.1"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sentences-name
    mode: name
  name: name
spec:
  ports:
  - name: api
    port: 5000
    protocol: TCP
    targetPort: 5000
    appProtocol: http
  selector:
    app: sentences-name
    mode: name
  type: ClusterIP
---
