apiVersion: v1
kind: Service
metadata:
  labels:
    app: sentences
    mode: sentence
  name: sentences
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    appProtocol: http
  selector:
    app: sentences
    mode: sentence
  type: NodePort
